default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") { "your_username" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "your_password" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: blog_with_ruby_development

test:
  <<: *default
  database: blog_with_ruby_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "blog_with_ruby_production" } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
