default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_with_ruby_development

test:
  <<: *default
  database: blog_with_ruby_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

 

  # Add these for Solid Cable
  cable:
    <<: *default
    database: <%= ENv['DATABASE_URL'].sub(/\/[^\/]*$/, '_cable') %>
    migrations_paths: db/cable_migrate