default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Chainsmoke") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: blog_with_ruby_development

test:
  <<: *default
  database: blog_with_ruby_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "blog_with_ruby_production") %>
    url: <%= ENV.fetch("DATABASE_URL") %>

  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "blog_with_ruby_production") %>
    url: <%= ENV.fetch("DATABASE_URL") %>

  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "blog_with_ruby_production") %>
    url: <%= ENV.fetch("DATABASE_URL") %>
