default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blog_with_ruby_development

test:
  <<: *default
  database: blog_with_ruby_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


production:
  primary: &primary_production
    <<: *default
    database: blog_with_ruby_production
    username: blog_with_ruby
    password: <%= ENV["BLOG_WITH_RUBY_DATABASE_PASSWORD"] %>

  cable:
    <<: *primary_production
    # give it a distinct DB name (or reuse primary if you want):
    database: blog_with_ruby_production_cable
    migrations_paths: db/cable_migrate
